"""dashboard 领域常量的唯一定义。"""

WATCHLIST_CATEGORIES = ("US", "A", "H")

PORTFOLIO_MARKETS: tuple[str, ...] = ("US", "A", "H")

DASHBOARD_QUOTE_TTL_SECONDS = 8

DASHBOARD_STATIC_INFO_TTL_SECONDS = 3600

DASHBOARD_CACHE_MAX_ENTRIES = 2000
