import type {
  ConfigDraft
} from "@/types/app";

export const CONFIG_PAYLOAD_KEYS_BY_DRAFT_KEY: Partial<Record<keyof ConfigDraft, string[]>> = {
  llm_provider: ["llm_provider", "llm_auth_mode"],
  llm_auth_mode: ["llm_provider", "llm_auth_mode"],
  llm_api_base: ["llm_api_base"],
  llm_model: ["llm_model"],
  llm_api_key: ["llm_api_key"],
  llm_codex_auth_file: ["llm_codex_auth_file"],
  llm_codex_api_base: ["llm_codex_api_base"],
  llm_codex_model: ["llm_codex_model"],
  llm_temperature: ["llm_temperature"],
  llm_max_output_tokens: ["llm_max_output_tokens"],
  llm_reasoning_effort: ["llm_reasoning_effort"],
  llm_tool_choice: ["llm_tool_choice"],
  embedding_auth_mode: ["embedding_auth_mode"],
  embedding_api_base: ["embedding_api_base"],
  embedding_model: ["embedding_model"],
  embedding_provider: ["embedding_provider"],
  embedding_api_key: ["embedding_api_key"],
  embedding_codex_auth_file: ["embedding_codex_auth_file"],
  embedding_codex_api_base: ["embedding_codex_api_base"],
  embedding_codex_model: ["embedding_codex_model"],
  workspace_dir: ["workspace_dir"],
  app_language: ["app_language"],
  auth_max_devices_per_user: ["auth_max_devices_per_user"],
  agent_max_steps: ["agent_max_steps"],
  agent_max_context_tokens: ["agent_max_context_tokens"],
  agent_max_context_turns: ["agent_max_context_turns"],
  agent_tool_allowlist: ["agent_tool_allowlist"],
  agent_allow_all_mcp_tools: ["agent_allow_all_mcp_tools"],
  multi_agent_enabled: ["multi_agent_enabled"],
  multi_agent_max_parallel_agents: ["multi_agent_max_parallel_agents"],
  multi_agent_max_tasks_per_batch: ["multi_agent_max_tasks_per_batch"],
  multi_agent_task_timeout_seconds: ["multi_agent_task_timeout_seconds"],
  multi_agent_default_max_steps: ["multi_agent_default_max_steps"],
  multi_agent_max_depth: ["multi_agent_max_depth"],
  multi_agent_dangerous_tools: ["multi_agent_dangerous_tools"],
  multi_agent_roles: ["multi_agent_roles"],
  knowledge_enabled: ["knowledge_enabled"],
  memory_enabled: ["memory_enabled"],
  memory_auto_curate_enabled: ["memory_auto_curate_enabled"],
  memory_curator_min_importance: ["memory_curator_min_importance"],
  memory_curator_min_confidence: ["memory_curator_min_confidence"],
  scheduler_enabled: ["scheduler_enabled"],
  tracing_enabled: ["tracing_enabled"],
  product_analytics_enabled: ["product_analytics_enabled"],
  telegram_enabled: ["telegram_enabled"],
  telegram_bot_token: ["telegram_bot_token"],
  telegram_chat_id: ["telegram_chat_id"],
  telegram_api_base: ["telegram_api_base"],
  telegram_parse_mode: ["telegram_parse_mode"],
  system_prompt: ["system_prompt"],
  mcp_servers_text: ["mcp_servers"],
  mcp_tool_timeout_seconds: ["mcp_tool_timeout_seconds"],
  longbridge_app_key: ["longbridge_app_key"],
  longbridge_auth_mode: ["longbridge_auth_mode"],
  longbridge_app_secret: ["longbridge_app_secret"],
  longbridge_access_token: ["longbridge_access_token"],
  longbridge_http_url: ["longbridge_http_url"],
  longbridge_quote_ws_url: ["longbridge_quote_ws_url"],
  search_api_url: ["search_api_url"],
  search_api_key: ["search_api_key"],
  debug: ["debug"],
};

export const PERSONAL_CONFIG_PAYLOAD_KEYS = new Set([
  "llm_provider",
  "llm_auth_mode",
  "llm_api_key",
  "llm_api_base",
  "llm_model",
  "llm_codex_auth_file",
  "llm_codex_api_base",
  "llm_codex_model",
  "llm_temperature",
  "llm_max_output_tokens",
  "llm_reasoning_effort",
  "llm_tool_choice",
  "embedding_auth_mode",
  "embedding_api_key",
  "embedding_api_base",
  "embedding_model",
  "embedding_provider",
  "embedding_codex_auth_file",
  "embedding_codex_api_base",
  "embedding_codex_model",
  "telegram_enabled",
  "telegram_bot_token",
  "telegram_chat_id",
  "telegram_api_base",
  "telegram_parse_mode",
  "mcp_servers",
  "mcp_tool_timeout_seconds",
  "longbridge_app_key",
  "longbridge_auth_mode",
  "longbridge_app_secret",
  "longbridge_access_token",
  "longbridge_http_url",
  "longbridge_quote_ws_url",
  "search_api_url",
  "search_api_key",
  "app_language",
  "agent_max_steps",
  "agent_max_context_tokens",
  "agent_max_context_turns",
  "multi_agent_enabled",
  "multi_agent_max_parallel_agents",
  "multi_agent_max_tasks_per_batch",
  "multi_agent_task_timeout_seconds",
  "multi_agent_default_max_steps",
  "multi_agent_max_depth",
  "knowledge_enabled",
  "memory_enabled",
  "memory_auto_curate_enabled",
  "memory_curator_min_importance",
  "memory_curator_min_confidence",
  "scheduler_enabled",
  "tracing_enabled",
  "product_analytics_enabled",
  "debug",
]);
