import type { AppConfig, ConfigDraft } from "@/types/app";

export function toDraft(config: AppConfig): ConfigDraft {
  return {
    ...config,
    llm_provider: config.llm_provider ?? "openai_compatible",
    llm_auth_mode: config.llm_auth_mode ?? "api_key",
    llm_codex_auth_file: config.llm_codex_auth_file ?? "",
    llm_codex_api_base: config.llm_codex_api_base ?? "https://chatgpt.com/backend-api/codex",
    llm_codex_model: config.llm_codex_model ?? "gpt-5.2-codex",
    llm_temperature: config.llm_temperature ?? 0,
    llm_max_output_tokens: config.llm_max_output_tokens ?? 0,
    llm_reasoning_effort: config.llm_reasoning_effort ?? "medium",
    llm_tool_choice: config.llm_tool_choice ?? "auto",
    embedding_auth_mode: config.embedding_auth_mode ?? "api_key",
    embedding_codex_auth_file: config.embedding_codex_auth_file ?? "",
    embedding_codex_api_base: config.embedding_codex_api_base ?? "https://chatgpt.com/backend-api/codex",
    embedding_codex_model: config.embedding_codex_model ?? "text-embedding-3-small",
    llm_api_key: "",
    embedding_api_key: "",
    telegram_bot_token: "",
    telegram_chat_id: config.telegram_chat_id ?? "",
    telegram_api_base: config.telegram_api_base ?? "https://api.telegram.org",
    telegram_parse_mode: config.telegram_parse_mode ?? "",
    longbridge_app_key: "",
    longbridge_app_secret: "",
    longbridge_access_token: "",
    longbridge_http_url: config.longbridge_http_url ?? "",
    longbridge_quote_ws_url: config.longbridge_quote_ws_url ?? "",
    agent_tool_allowlist: config.agent_tool_allowlist ?? [],
    agent_allow_all_mcp_tools: config.agent_allow_all_mcp_tools ?? true,
    mcp_servers_text: JSON.stringify(config.mcp_servers ?? {}, null, 2),
    mcp_tool_timeout_seconds: config.mcp_tool_timeout_seconds ?? 60,
  };
}
